add wrflow changes

diff --git a/.github/workflows/sync_mirror.yml b/.github/workflows/sync_mirror.yml
--- a/.github/workflows/sync_mirror.yml
+++ b/.github/workflows/sync_mirror.yml
@@ -13,83 +13,61 @@ jobs:
       - name: Trigger mirror on aravindraveendran-mpl/dependencyrepo
         id: mirror_mobile-league-ios-contract
         run: |
-          curl -L -X POST \
-            -H "Authorization: Bearer ${{ secrets.PACKAGES_GITHUB_PAT }}" \
-            -H "Accept: application/vnd.github+json" \
-            -H "X-GitHub-Api-Version: 2022-11-28" \
-            https://api.github.com/repos/aravindraveendran-mpl/dependencyrepo/actions/workflows/sync_mirror.yml/dispatches \
-            -d '{"ref":"main"}'
+          gh workflow run sync_mirror.yml --ref main --repo aravindraveendran-mpl/dependencyrepo
+          echo "Waiting for 10 seconds to allow the workflow to start..."
+          sleep 10
 
-          response=$(curl https://api.github.com/repos/aravindraveendran-mpl/dependencyrepo/actions/workflows/sync_mirror.yml/runs \
-            -H "Authorization: Bearer ${{ secrets.PACKAGES_GITHUB_PAT }}")
-          echo "Response: $response"
+          run_id=$(gh run list --workflow=sync_mirror.yml --branch=main --limit=1 --repo aravindraveendran-mpl/dependencyrepo --json databaseId --jq '.[0].databaseId')
+          echo "Run ID: $run_id"
 
-          # Extract the run ID from the response
-          RUN_ID=$(echo $response | jq -r '.workflow_runs[0].id')
-          echo "Run ID: $RUN_ID"
-
-          echo "run_id=${RUN_ID}" >> $GITHUB_OUTPUT
+          if [ "${{ steps.get-run-id.outputs.run_id }}" == "null" ]; then
+            echo "Run ID is nil. Exiting..."
+            exit 1
+          else
+            echo "::set-output name=run_id::$run_id"
+          fi
 
       - name: Trigger mirror on aravindraveendran-mpl/dependencyrepo
         id: mirror_mobile-league-ios-validic
         run: |
-          response=$(curl -X POST \
-            https://api.github.com/repos/aravindraveendran-mpl/dependencyrepo/actions/workflows/sync_mirror.yml/dispatches \
-            -H "Authorization: Bearer ${{ secrets.PACKAGES_GITHUB_PAT }}" \
-            -H "Accept: application/vnd.github+json" \
-            -d '{"ref":"main"}')
+          gh workflow run sync_mirror.yml --ref main --repo aravindraveendran-mpl/dependencyrepo
+          echo "Waiting for 10 seconds to allow the workflow to start..."
+          sleep 10
 
-          echo "Response: $response"
+          run_id=$(gh run list --workflow=sync_mirror.yml --branch=main --limit=1 --repo aravindraveendran-mpl/dependencyrepo --json databaseId --jq '.[0].databaseId')
+          echo "Run ID: $run_id"
 
-          # Extract the run ID from the response
-          RUN_ID=$(echo $response | jq -r '.workflow_run.id')
-          echo "Run ID: $RUN_ID"
-
-          echo "run_id=${RUN_ID}" >> $GITHUB_OUTPUT
+          if [ "${{ steps.get-run-id.outputs.run_id }}" == "null" ]; then
+            echo "Run ID is nil. Exiting..."
+            exit 1
+          else
+            echo "::set-output name=run_id::$run_id"
+          fi
 
       - name: Wait for both dependent mirrors to complete
         id: wait_for_dependant_mirrors
-        uses: actions/github-script@v5
-        with:
-          script: |
-            const token = ${{ secrets.PACKAGES_GITHUB_PAT }};
+        run: |
+          mobile-league-ios-contract_run_id=${{ steps.mirror_mobile-league-ios-contract.outputs.run_id }}
+          while [ "$(gh run view $mobile-league-ios-contract_run_id --repo aravindraveendran-mpl/dependencyrepo --json conclusion --jq '.conclusion')" == "null" ]; do
+            echo "Waiting for workflow aravindraveendran-mpl/dependencyrepo to complete..."
+            sleep 10
+          done
+          mobile-league-ios-contract_run_conclusion=$(gh run view $mobile-league-ios-contract_run_id --repo aravindraveendran-mpl/dependencyrepo --json conclusion --jq '.conclusion')
+          echo "${mobile-league-ios-contract_run) completed with conclusion: $(mobile-league-ios-contract_run_conclusion)"
+          if [ "$mobile-league-ios-contract_run_conclusion" != "success" ]; then
+            echo "Workflow failed. Exiting..."
+            exit 1
+          fi
 
-            const checkWorkflowStatus = async (run_id, repo) => {
-              let status;
-              let conclusion;
+          mobile-league-ios-validic_run_id=${{ steps.mirror_mobile-league-ios-validic.outputs.run_id }}
+          while [ "$(gh run view $mobile-league-ios-validic_run_id --repo aravindraveendran-mpl/dependencyrepo --json conclusion --jq '.conclusion')" == "null" ]; do
+            echo "Waiting for workflow aravindraveendran-mpl/dependencyrepo to complete..."
+            sleep 10
+          done
+          mobile-league-ios-validic_run_conclusion=$(gh run view $mobile-league-ios-validic_run_id --repo aravindraveendran-mpl/dependencyrepo --json conclusion --jq '.conclusion')
+          echo "${mobile-league-ios-validic_run_id} completed with conclusion: $mobile-league-ios-contract_run_conclusion"
+          if [ "$mobile-league-ios-validic_run_conclusion" != "success" ]; then
+            echo "Waiting for workflow aravindraveendran-mpl/dependencyrepo to complete..."
+            exit 1
+          fi
 
-              do {
-                // Poll the workflow status
-                const response = await fetch(
-                  `https://api.github.com/repos/${repo}/actions/runs/${run_id}`,
-                  {
-                    method: 'GET',
-                    headers: {
-                      'Authorization': `Bearer ${token}`,
-                      'Accept': 'application/vnd.github+json'
-                    }
-                  }
-                );
-                const data = await response.json();
-                status = data.status;
-                conclusion = data.conclusion;
-
-                console.log(`Workflow status for ${repo}, ${run_id}: ${status}, and conclusion ${conclusion}`);
-                
-                // Wait for 30 seconds before checking again
-                if (status !== 'completed') {
-                  await new Promise(resolve => setTimeout(resolve, 30000));
-                }
-              } while (status !== 'completed');
-
-              if (conclusion !== 'success') {
-                throw new Error('The workflow run on ${repo} failed')
-              }
-              console.log('Workflow run in ${repo} has completed!');
-            };
-
-            const mirror_mobile-league-ios-contract_run_id = '${{ steps.mirror_mobile-league-ios-contract.outputs.run_id }}';
-            const mirror_mobile-league-ios-validic_run_id = '${{ steps.mirror_mobile-league-ios-validic.outputs.run_id }}';
-
-            await checkWorkflowStatus(mirror_mobile-league-ios-contract_run_id, 'aravindraveendran-mpl/dependencyrepo');
-            await checkWorkflowStatus(mirror_mobile-league-ios-validic_run_id, 'aravindraveendran-mpl/dependencyrepo');
